version: "2"
linters:
  enable:
    - bidichk
    - bodyclose
    - copyloopvar
    - decorder
    - errchkjson
    - errorlint
    - forbidigo
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - lll
    - nilerr
    - nilnil
    - nolintlint
    - predeclared
    - revive
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace
  settings:
    funlen:
      ignore-comments: true
    gosec:
      excludes:
        - G304
    govet:
      disable:
        - fieldalignment
      enable-all: true
    lll:
      line-length: 130
    revive:
      rules:
        - name: var-naming
          arguments:
            - []
  exclusions:
    generated: lax
    rules:
      - linters:
          - bodyclose
          - errcheck
          - errchkjson
          - funlen
          - goconst
          - gosec
          - govet
          - unparam
        path: _test\.go
      - linters:
          - funlen
          - govet
        path: \.gen\.go
      - linters:
          - lll
        source: '^//go:generate '
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
